<a href="https://colab.research.google.com/github/kiyong21c/pytorch_tutorial/blob/main/20220708_Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# activation functions

# output = w*x + b
# output = activation_function(output)
import torch
import torch.nn as nn
import torch.nn.functional as F

x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

# softmax : 합이 1이 되는 비중을 갖도록함
# sofmax with torch
output = torch.softmax(x, dim=0)
print(output)
# sofmax with torch.nn
sm = nn.Softmax(dim=0)
output = sm(x)
print(output)

# sigmoid : 각각 0~1사이의 비중을 갖도록
# sigmoid with torch
output = torch.sigmoid(x)
print(output)
# sigmoid with torch.nn
s = nn.Sigmoid()
output = s(x)
print(output)

# #tanh
# output = torch.tanh(x)
# print(output)
# t = nn.Tanh()
# output = t(x)
# print(output)

# # relu
# output = torch.relu(x)
# print(output)
# relu = nn.ReLU()
# output = relu(x)
# print(output)

# # leaky relu
# output = F.leaky_relu(x)
# print(output)
# lrelu = nn.LeakyReLU()
# output = lrelu(x)
# print(output)

#nn.ReLU() creates an nn.Module which you can add e.g. to an nn.Sequential model.
#torch.relu on the other side is just the functional API call to the relu function,
#so that you can add it e.g. in your forward method yourself.

# option 1 (create nn modules)
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()        # nn.ReLU()라는 층을 만들어 사용
        self.linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()  # nn.Sigmoid()라는 층을 만들어 사용
    
    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

# option 2 (use activation functions directly in forward pass)
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        # relu 층을 만들지 않음
        self.linear2 = nn.Linear(hidden_size, 1)
        # sigmoid 층을 만들지 않음

    
    def forward(self, x):
        out = torch.relu(self.linear1(x)) # torch.relu() 함수형 API 사용하여 relu 기능 수행
        out = torch.sigmoid(self.linear2(out))
        return out

tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.2689, 0.7311, 0.8808, 0.9526])
tensor([0.2689, 0.7311, 0.8808, 0.9526])
